### ISSUE TITLE
Better documentation for Images plugin

### ISSUE THREAD

**Issue by balupton** [docpad-archive/extras#2]
The [Images Plugin](https://github.com/bevry/docpad-extras/tree/master/plugins/images) could do better documentation, and perhaps could even be changed to be a bit more generic - e.g. call it readdir or something.

Your thoughts @msutherl ?

**Comment by DjebbZ** [comment]
I would like better docs, because I don't even understand how to use it. If being more generic means using the new `docpad.cson` file to configure it then I'm all for it. @msutherl or @balupton could you explain me how it works ? When and where to place the real images files ? I'll be then happy to update it.

**Comment by balupton** [comment]
I don't understand either. I think it is deprecated now that everything is in the database as of DocPad 5.2. Will remove it in the next batch.

**Comment by flowerornament** [comment]
Did you guys read the README? I can improve the docs, but perhaps you can let me know what it is about the existing documentation that is confusing.

> docpad-images uses folders named according to the <code>basename</code> (filename of a document minus extension) property of each document.
> 
> Running <code>docpad generate</code> with docpad-images installed will automatically create a set of folders in <code>/src/public/images/</code>. Images in <code>/src/public/images/[basename]/</code> will subsequently be accesible to the document with that basename during document rendering (i.e. in a template or in a plugin that is triggered after the initial <code>render</code> pass).
> 
> (If you don't want folders automatically created for every document, you can comment lines 18 and 19 in the plugin and create them manually. If you want to use different path-names, you can also modify the plugin directly to do this.)

from https://github.com/bevry/docpad-extras/blob/master/plugins/images/README.md

**Comment by flowerornament** [comment]
Documentation clarified a bit with an example in: https://github.com/bevry/docpad-extras/commit/0ce1ad0ea6ce52903b9b8bc260665945461c7da0

**Comment by DjebbZ** [comment]
It's much clearer where we should put the images now, thanks to the example. Without the example, it was somehow hidden between the lines (at least according to me). There's a mistake tough in the example : I think the path for images is `images/doc1/img1.jpg` etc. (I added `doc1`). Am I right ?

**Comment by flowerornament** [comment]
@DjebbZ you're right – fixed in: https://github.com/bevry/docpad-extras/tree/280811548f8cb29c6b869ec4c52ffecd81338ded – good catch!

**Comment by DjebbZ** [comment]
Thank you @msutherl :)

As you may know (or not), I'm basically writing the documentation of the whole DocPad thing. Would you mind letting me rewrite the README file of the images plugin to make it a bit clearer ?

-- edit : not "more clearer", "clearer" is enough :)

**Comment by flowerornament** [comment]
@DjebbZ Please do! Thanks for doing the documentation – it will be a huge help.

**Comment by DjebbZ** [comment]
Done in https://github.com/bevry/docpad-extras/commit/51c8c06b77aea2706416791afa0443f88d1eff71

But I removed every statement about automatic folder creation. My understanding of the plugin is that, if no `src/public/images/doc1` exists for `doc1.html.coffee|eco|whatever`, the plugin will create it for us during the next generation. Which is useless because there will be no images inside. It's like using `docpad generate` for `mkdir`, right ? I didn't not remove the code for this, as it may be useful in some case, and could even be considered as a helper to get started faster. What's your opinion ? And your use case for automatic folder creation ?

I'm also thinking that this automatic folder creation could use not only the basename, but the full document path under `src/documents`. It would prevent filename collisions, since one could have several `index.html` files spread in various folders. What do you think ?

**Comment by flowerornament** [comment]
> It's like using docpad generate for mkdir, right ?

Exactly. It's so that you don't have to manually create folders for all of your documents, which could take awhile if you have a lot of documents. It's also a form of self-documentation. You don't have to worry about "where do I create that folder and what is it supposed to be called?"

> I'm also thinking that this automatic folder creation could use not only the basename, but the full document path under src/documents. It would prevent filename collisions, since one could have several index.html files spread in various folders. What do you think ?

This should be done if it's not already. Feel free to do it now if you like, otherwise I will try to get to it in the next two days.

**Comment by DjebbZ** [comment]
Agree on the helper side of the automatic folder creation. In an ideal world, when @balupton would have created a better [CLI architecture](https://github.com/bevry/docpad/issues/187), the folder creation could be a CLI of its own.

About the name collisions, I'll check tonight or tomorrow. If not, feel free to do it as you like.
