### ISSUE TITLE
HighlightJS & Marked Incompatibilities

### ISSUE THREAD

**Issue by iammerrick** [docpad-archive/extras#24]
To re-create this problem create a new docpad project with marked and highlightjs docpad plugins. Then set the marked configuration options to sanitize: false. This is useful for embedding iframes and other markup in your otherwise markdown post. Then JSHighlight will no longer highlight the your code.

**Comment by iammerrick** [comment]
It looks like it may be the way docpad merges configuration. I thought I could perhaps just override on property, instead it looks like I might have to specify all options even if I want to change just one...

### Works:

``` coffeescript
  plugins:
    marked:
      markedOptions:
        pedantic: false
        gfm: true
        sanitize: false
        highlight: null
```

### Doesn't Work:

``` coffeescript
  plugins:
    marked:
      markedOptions:
        sanitize: false
```

The only difference in the one that works is I explicitly declare the same options that are already set inside of the marked implementation.

**Comment by balupton** [comment]
Interesting. I've currently got a lot on my plate, so if someone can look into this more in the meantime that will be grand.

**Comment by chase** [comment]
If I get time, I'll try to look into this. Mainly because both plugins are my fault, haha.

Never thought about using sanitize.

Certainly one way would be to use Marked's ability to assign a syntax highlighter, the plugin for Highlight.js would ignore sanitized Markdown files that have this problem while the Marked plugin deals with it directly (and more efficiently, for that matter.)

**Comment by balupton** [comment]
closing due to age
